### ISSUE TITLE
v1.0.0.7 made breaking changes

### ISSUE THREAD

**Issue by Allon-Guralnek** [reustmd/DataAnnotationsValidatorRecursive#13]
Hello,

We're using your library (thanks for it!) and have just updated our packages to the latest version. This caused the following error during runtime:

> [System.MissingMethodException] Method not found: 'Boolean DataAnnotationsValidator.DataAnnotationsValidator.TryValidateObjectRecursive(!!0, System.Collections.Generic.List`1<System.ComponentModel.DataAnnotations.ValidationResult>)'.

This is probably caused by changes made to the signature of the method. We had to revert to v1.0.0.1 in order to fix this issue. Please be aware that such breaking changes should only be done in a new major version, as per [Semantic Versioning](http://semver.org/), to avoid breaking your users.

**Comment by reustmd** [comment]
Hi @Allon-Guralnek,

I'm sorry for any pain, but the public signatures have not changed, which is why I didn't up the major version. What signature are you seeing when you install the package?

cheers,
Mike

**Comment by reustmd** [comment]
in the meantime, I unlisted the 1.0.0.7 update that's giving you trouble, and upped the version to 1.0.1

**Comment by Allon-Guralnek** [comment]
You did change the public signatures. Here is a comparison of 1.0.0.1 and 1.0.1:

![dataannotationsvalidator](https://user-images.githubusercontent.com/1709453/27854411-65505f9a-616f-11e7-8036-87893e95d50a.png)

Adding a parameter is a breaking change, even if it is an optional parameter. You must remember that optional parameters are a compiler trick and you can only match a callsite that's missing a parameter to a method that has an optional parameter during compile time (the compiler inserts the default value in the callsite). But if not re-compilation was performed (like in this case, the assembly was just replace), then the call will fail with MissingMethodException since the callsite doesn't match the method signature.

If you want to add a parameter in a public library without making a breaking change, you must add it as an overload, not an optional parameter.

**Comment by reustmd** [comment]
Thanks for the clarification @Allon-Guralnek. Please excuse my confusion, that code change was made a year ago by another contributor, I didn't realize it wasn't part of the latest nuget 1.0.0.1.

The nuget packaging is managed by yet another contributor, and it happens automatically via CI (apparently it wasn't reliable back in August when this code shipped, and it failed to ship a new version). So, my surprise is that when I made other unrelated changes and they shipped via nuget this week, those picked up the changes from 2016 and broke your usage.

Anywho, I'm waiting to hear back from the person managing nuget to turn off their own CI. Once they do so, I'll kill the versions past `1.0.0.1` and re-release this as `2.0`.

**Comment by Allon-Guralnek** [comment]
Thanks 👍

**Comment by reustmd** [comment]
I think we're good to go now @Allon-Guralnek
