### ISSUE TITLE
Strong name signature not valid for this assembly

### ISSUE THREAD

**Issue by EranOfer** [reustmd/DataAnnotationsValidatorRecursive#14]
Hi,
After I updated to version 2.0 I'm getting exception from ClickOnce:

Following failure messages were detected:
		+ Strong name signature not valid for this assembly DataAnnotationsValidator.dll.

To solve the problem I compiled the code locally and included it with my application without a signature. 
Version 1.x worked fine.

**Comment by halovanic** [comment]
I see the same in my IIS application when pulling 2.0 from NuGet.  Also of note is that the version number in the DLL seems to have gone backwards from 1.0.0.1 to 1.0.0.0: only the NuGet path shows 2.0.

Thanks,
Alex

**Comment by ali-joghataei** [comment]
I have the same issue

**Comment by reustmd** [comment]
I just published version 2.1.0 (might still take a while to update the nuget index before you can see it to upgrade) after rebuilding with signature, please lemme know if you still have issues
