### ISSUE TITLE
License and nuget package

### ISSUE THREAD

**Issue by borismod** [reustmd/DataAnnotationsValidatorRecursive#2]
Could you please choose a license and add it to the repo?
Could you please publish this project as a nuget package? I can help with that if needed

**Comment by reustmd** [comment]
@borismod I have added the MIT license. Should give you the freedom to do as you like.

It's been many years since I've done .NET development and I'm not setup for it. Feel free to run at turning this into a nuget package if you'd like to.

**Comment by borismod** [comment]
@reustmd cool! I'll add nuget packaging via CI.
